# Generated by Django 5.2.6 on 2026-02-12 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='company',
        ),
        migrations.AddField(
            model_name='lead',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
